<?php

return [
    'file-name' => 'critical-routes.json',

    /**
     * the suffix for the css files generated by critical css. this needs to be the same as defined in the `.criticalCss()`
     * function in mix.
     */
    'suffix' => '_critical.min',
];
